
const canvas = document.querySelector('canvas');
const c = canvas.getContext('2d');
const scoreAmount = document.querySelector('#scoreAmount');
const level = document.querySelector('#level');
const startBox = document.querySelector('.startBox');
const endBox = document.querySelector('.endBox');
const finalScoreNumber = document.querySelector('#finalscorenumber');
const namescore = document.querySelector('#namescore');
const lb = document.querySelector('.lb');
const grid = document.querySelector('.grid-container');
const offsetMatrixBg = 140;
const powerUpIntervalTimer = 10000;
const enemiesIntervalTimer = 2500;
const pointForElimination = 50;
const pointForHit = 10;
const enemyShrinkFactor = 1.2;
const ROCKET_FULL_AMMO = 10;
const MG_FULL_AMMO = 60;
const DEFAULT_AMMO_COLOR = 'white';
const perfectFrameTime = 1000 / 60;
const deltaTime = 200;
const AMMO_VELOCITY_DELTA = 3;


let centerX;
let centerY;
let player;
let playerBlackEffect;
let playerGrowEffect;
let projectiles;
let enemis;
let powerups;
let particles;
let scoreDelta;
let score;
let matrixBg;
let isStarted = false;
let enemiesIntervalId;
let powerupIntervalId;
let lastKilledEnemyColor;
let animationId;
let isEliminated;
let keys;
let rocketGunRatio;
let current_ammo;
let isPowered;
let curr_mouse_pos;
let isMachineGun;
let isMouseDown;
let lastTimestamp;
let deltaAmmo;